os:
  - linux

language: go

go:
  - 1.12.x

env:
  global:
    - GOTFLAGS="-race"
  matrix:
    - BUILD_DEPTYPE=gomod

# disable travis install
install:
  - true

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false

#go_import_path: github.com/google/uuid

script:
  - go get -v -t -d ./...
  - echo "start to build and test speedtest."
  - bash build.sh run_linux
  - echo "finish"
